import { sqliteTable, text, integer, real, index } from "drizzle-orm/sqlite-core";

export const reviews = sqliteTable(
  "reviews",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    title: text("title").notNull(),
    slug: text("slug").notNull().unique(),
    content: text("content").notNull(),
    excerpt: text("excerpt"),
    featuredImage: text("featured_image"),
    reviewType: text("review_type").notNull(),
    ratingOverall: real("rating_overall"),
    ratingValue: real("rating_value"),
    ratingQuality: real("rating_quality"),
    ratingComfort: real("rating_comfort"),
    ratingFamily: real("rating_family"),
    pros: text("pros"),
    cons: text("cons"),
    wouldRecommend: text("would_recommend"),
    finalVerdict: text("final_verdict"),
    status: text("status").default("draft"),
    scheduledAt: text("scheduled_at"),
    publishedAt: text("published_at"),
    updatedAt: text("updated_at"),
    createdAt: text("created_at"),
    deletedAt: text("deleted_at"),
    seoTitle: text("seo_title"),
    seoDescription: text("seo_description"),
    isVisible: integer("is_visible", { mode: "boolean" }).default(true),
    isPinned: integer("is_pinned", { mode: "boolean" }).default(false),
    isHighlighted: integer("is_highlighted", { mode: "boolean" }).default(false),
    pinnedAt: text("pinned_at"),
  },
  (table) => ({
    idxReviewsStatus: index("idx_reviews_status").on(table.status),
    idxReviewsPublishedAt: index("idx_reviews_published_at").on(table.publishedAt),
    idxReviewsDeletedAt: index("idx_reviews_deleted_at").on(table.deletedAt),
    idxReviewsStatusDeletedAt: index("idx_reviews_status_deleted_at").on(table.status, table.deletedAt),
  })
);
